"use strict";
exports.__esModule = true;
exports.server = void 0;
var body_parser_1 = require("body-parser");
var express_1 = require("express");
var app = express_1["default"]();
app.use(body_parser_1["default"].json());
app.use(body_parser_1["default"].urlencoded());
app.get('/test', function (req, res) { return res.send(new Date().toISOString); });
exports.server = app.listen(8080, function () { return console.log("server running on port 8080"); });
